### ISSUE TITLE
tk vs. toolkit

### ISSUE THREAD

**Issue by sebastianbergmann** [tideways/toolkit#3]
Documentation (`README.md`) says `tk` but after `go get github.com/tideways/toolkit` I have a binary named `toolkit` in my `$GOPATH`.

**Comment by beberlei** [comment]
yes, the binary will be `tk` - i need to implement #2 to get it all working.

Maybe i will find another name, toolkit is too generic and `tk` is a bit risky as a short name to find duplicates, although from my first search this is not yet used.

**Comment by beberlei** [comment]
Fixed in https://github.com/tideways/toolkit/releases/tag/v0.2
